
/* ----- Authentication ----- */
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";

/* ----- Queue ----- */
export const FETCH_QUEUE_START = "FETCH_QUEUE_START";
export const FETCH_QUEUE_SUCCESS = "FETCH_QUEUE_SUCCESS";
export const FETCH_QUEUE_FAIL = "FETCH_QUEUE_FAIL";

export const ADD_TO_QUEUE_START = "ADD_TO_QUEUE_START";
export const ADD_TO_QUEUE_SUCCESS = "ADD_TO_QUEUE_SUCCESS";
export const ADD_TO_QUEUE_FAIL = "ADD_TO_QUEUE_FAIL";

export const DELETE_FROM_QUEUE_START = "DELETE_FROM_QUEUE_START";
export const DELETE_FROM_QUEUE_SUCCESS = "DELETE_FROM_QUEUE_SUCCESS";
export const DELETE_FROM_QUEUE_FAIL = "DELETE_FROM_QUEUE_FAIL";

export const DONE_IN_QUEUE_START = "DONE_IN_QUEUE_START";
export const DONE_IN_QUEUE_SUCCESS = "DONE_IN_QUEUE_SUCCESS";
export const DONE_IN_QUEUE_FAIL = "DONE_IN_QUEUE_FAIL";

export const FETCH_SUBJECTS_START = "FETCH_SUBJECTS_START";
export const FETCH_SUBJECTS_SUCCESS = "FETCH_SUBJECTS_SUCCESS";
export const FETCH_SUBJECTS_FAIL = "FETCH_SUBJECTS_FAIL";

